package com.github.mmolimar.ksql.jdbc

import java.sql.{Connection, ResultSet, SQLWarning, Statement}

import com.github.mmolimar.ksql.jdbc.Exceptions._
import com.github.mmolimar.ksql.jdbc.resultset.KsqlResultSet
import io.confluent.ksql.rest.client.KsqlRestClient

class KsqlStatement(private val ksqlClient: KsqlRestClient, val timeout: Long = 0)
  extends Statement with WrapperNotSupported {

  override def setMaxFieldSize(max: Int): Unit = throw NotSupported("setMaxFieldSize")

  override def getMoreResults: Boolean = throw NotSupported("getMoreResults")

  override def getMoreResults(current: Int): Boolean = throw NotSupported("getMoreResults")

  override def clearWarnings(): Unit = throw NotSupported("clearWarnings")

  override def getGeneratedKeys: ResultSet = throw NotSupported("getGeneratedKeys")

  override def closeOnCompletion(): Unit = throw NotSupported("closeOnCompletion")

  override def cancel(): Unit = throw NotSupported("cancel")

  override def getResultSet: ResultSet = throw NotSupported("getResultSet")

  override def isPoolable: Boolean = throw NotSupported("isPoolable")

  override def setPoolable(poolable: Boolean): Unit = throw NotSupported("setPoolable")

  override def setCursorName(name: String): Unit = throw NotSupported("setCursorName")

  override def getUpdateCount: Int = throw NotSupported("getUpdateCount")

  override def addBatch(sql: String): Unit = throw NotSupported("addBatch")

  override def getMaxRows: Int = throw NotSupported("getMaxRows")

  override def execute(sql: String): Boolean = ksqlClient.makeKsqlRequest(fixSql(sql)).isSuccessful

  //TODO
  override def execute(sql: String, autoGeneratedKeys: Int): Boolean = execute(sql)

  //TODO
  override def execute(sql: String, columnIndexes: Array[Int]): Boolean = execute(sql)

  //TODO
  override def execute(sql: String, columnNames: Array[String]): Boolean = execute(sql)

  override def executeQuery(sql: String): ResultSet = {
    val response = ksqlClient.makeQueryRequest(fixSql(sql))
    if (response.isErroneous)
      throw KsqlQueryError(s"Error executing query '${sql}'. " +
        s"Error: ${response.getErrorMessage.getMessage}")

    response.getResponse
  }

  override def getResultSetType: Int = throw NotSupported("getResultSetType")

  override def setMaxRows(max: Int): Unit = throw NotSupported("setMaxRows")

  override def getFetchSize: Int = throw NotSupported("getFetchSize")

  override def getResultSetHoldability: Int = throw NotSupported("getResultSetHoldability")

  override def setFetchDirection(direction: Int): Unit = throw NotSupported("setFetchDirection")

  override def getFetchDirection: Int = throw NotSupported("getFetchDirection")

  override def getResultSetConcurrency: Int = throw NotSupported("getResultSetConcurrency")

  override def clearBatch(): Unit = throw NotSupported("clearBatch")

  override def close(): Unit = throw NotSupported("close")

  override def isClosed: Boolean = throw NotSupported("isClosed")

  override def executeUpdate(sql: String): Int = throw NotSupported("executeUpdate")

  override def executeUpdate(sql: String, autoGeneratedKeys: Int): Int = throw NotSupported("executeUpdate")

  override def executeUpdate(sql: String, columnIndexes: Array[Int]): Int = throw NotSupported("executeUpdate")

  override def executeUpdate(sql: String, columnNames: Array[String]): Int = throw NotSupported("executeUpdate")

  override def getQueryTimeout: Int = throw NotSupported("getQueryTimeout")

  override def getWarnings: SQLWarning = throw NotSupported("getWarnings")

  override def setFetchSize(rows: Int): Unit = throw NotSupported("setFetchSize")

  override def setQueryTimeout(seconds: Int): Unit = throw NotSupported("setQueryTimeout")

  override def executeBatch(): Array[Int] = throw NotSupported("executeBatch")

  override def setEscapeProcessing(enable: Boolean): Unit = throw NotSupported("setEscapeProcessing")

  override def getConnection: Connection = throw NotSupported("getConnection")

  override def getMaxFieldSize: Int = throw NotSupported("getMaxFieldSize")

  override def isCloseOnCompletion: Boolean = throw NotSupported("isCloseOnCompletion")

  private def fixSql(sql: String) = if (sql.trim.endsWith(";")) sql else sql + ";"

  private implicit def toResultSet(stream: KsqlRestClient.QueryStream): ResultSet = new KsqlResultSet(stream, timeout)

}
